### PR TITLE
Adding typecasts, write(buf, len) and write(const char* buf)

### PR DESCRIPTION
**Pull request by rvdbreemen**
I needed some typecases, write(const char*) and write(buf, len) to make it work for me. Could not get my code compiled without this.

### CODE REVIEW

**Comment by rvdbreemen** [comment]
I needed some typecases, write(const char*) and write(buf, len) to make it work for me. Could not get my code compiled without this.

**Comment by rvdbreemen** [comment]
Bugfix: Removed the matchBanner from read(). As it passed a &ch to a matchBanner (const char *buf, int len). 
Also rewrote read and available in same style...

**Comment by hvxl** [comment]
The different versions of the write method should be added. Although many of them would only be needed in unrealistic scenarios. But they don't consume any space when not used, so it doesn't hurt.

The other proposed changes are unnecessary, or even incorrect. Removing the call to matchBanner breaks the firmware version detection. Without that, an upgrade will not transfer the EEPROM settings during an upgrade. The metchBanner method can be simplified, though.

**Comment by hvxl** [comment]
Cherry-picked the correct commits and merged them in commit 6d1ab21.

**Pull request closed without merging**
